services:
  qdrant:
    image: qdrant/qdrant:gpu-nvidia-latest
    container_name: qdrant
    ports:
      - '6333:6333'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
